### ISSUE TITLE
Remove run-constraint on glibc>=2.32 on aarch

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/dask-sql-feedstock#66] opened 2023-07-05 14:29 UTC
AFAIU the TLS allocation situation, it's not _absolutely_ required to use newer glibc, i.e. things can still be "solved" by ensuring the libraries that require static TLS allocations come first (e.g. by reordering imports), see also: https://github.com/conda-forge/conda-forge.github.io/issues/1551

In particular, glibc 2.32 is very aggressive, and is only supported by around ~15% of Python users ([details](https://mayeut.github.io/manylinux-timeline/)[^1]). It also switches off the testing here, which is IMO worse than living with these TLS allocation problems (because we might end up pushing packages that seem to build but are broken).

CC @conda-forge/dask-sql @jakirkham 

[^1]: see the plot "glibc version (across non-EOL Python versions)"  for the consumer-side statistics. This only shows percentages for >=2.31 and >=2.34, but looking at https://github.com/mayeut/pep600_compliance/, there are no major distros using glibc 2.32 & 2.33 that aren't already EOL, so I think the percentage for >=2.34 will apply almost unchanged for >=2.32.

**Comment by charlesbluca** [comment] 2023-07-05 19:57
Thanks for raising this issue! Looks like you're correct in that reordering imports is sufficient to unblock imports of dask-sql; on an aarch machine with `glibc<2.32` the following works:

```python
import dask_planner.rust  # static TLS allocations happen here
import dask_sql  # would normally fail
```

Though imports of libraries using OpenMP (such as sklearn) fail after the fact:

```python
>>> import sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dask-sql/micromamba/envs/test-dask-sql-conda/lib/python3.10/site-packages/sklearn/__init__.py", line 83, in <module>
    from .utils._show_versions import show_versions
  File "/home/dask-sql/micromamba/envs/test-dask-sql-conda/lib/python3.10/site-packages/sklearn/utils/_show_versions.py", line 14, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: /home/dask-sql/micromamba/envs/test-dask-sql-conda/lib/python3.10/site-packages/sklearn/utils/../../../../libgomp.so.1: cannot allocate memory in static TLS block
```

Also worth noting that setting `LD_PRELOAD` to the path of dask-sql's compiled binary allows us to import both dask-sql and sklearn, though this may not always be possible to set.

Sounds like the preferred solution here would be to add this extra import and remove the glibc constraint?

**Comment by h-vetinari** [comment] 2023-07-05 21:23
> Sounds like the preferred solution here would be to add this extra import and remove the glibc constraint?

I think the constraint is just too conservative/restrictive. Any user on an older version would still be exactly as affected to the overall situation, only now with an older dask-sql version. And for those with a new enough glibc, we still might end up shipping broken packages due to lack or testing.

I'd say that if there's any way of making this work, with older glibc, we should remove the constraint, and document the workarounds (I don't think we can really affect import order from within the feedstock packaging)

**Comment by charlesbluca** [comment] 2023-07-18 23:11
Opened https://github.com/dask-contrib/dask-sql/pull/1201 to frontload the libraries that required static TLS allocations - once I've verified that this resolves the import errors on aarch64 with `glibc<2.32` we should be safe to remove the constraint and switch back on testing for aarch64 packages

**Comment by charlesbluca** [comment] 2023-07-19 14:17
Confirmed that https://github.com/dask-contrib/dask-sql/pull/1201 resolved the import issues and merged 🎉

Do you have any preference how we propagate that to the feedstock? Our next release will contain these changes but I suppose it's possible to patch the source code with the fix and remove the constraint in a new build of 2023.6.0

**Comment by h-vetinari** [comment] 2023-07-19 14:25
Cool thanks! It depends a bit when the next release is planned. If it's going to be >1 month, I think we should backport.

**Closed as completed** 2023-08-03 20:35 UTC
